### ISSUE TITLE
Using the patched miopen .deb throws warning xnack "off" in gfx803

### ISSUE THREAD

**Issue by Davidportlouis** [xuhuisheng/rocm-gfx803#1]
I have followed the steps listed in this repo's README.md to install rocm-dev, rocm-lib and other .deb's provided in the links, I'm currently in Ubuntu 20.04 LTS, Kernel 5.11.0-25-generic, My GPU is RX 550 (gfx804) Polaris 11, rocm 4.2. After installation I tried out some benchmark using resnet18 and cifar10. That is when I was greeted by this `warning: xnack 'Off' was requested for a processor that does not support it!`. Fortunately my training proceeded without ant error or problems, just wanted to report this warning popping off each time. I have attached a screenshot of my training when the warning pops.

![Screenshot from 2021-08-08 21-44-47](https://user-images.githubusercontent.com/18904157/128638732-949b6b44-de31-4684-9367-324efb116dda.png)

**Comment by xuhuisheng** [comment]
There is an already known issue, that miopen treat xnack option different with hip.

https://github.com/xuhuisheng/rocm-build/blob/master/gfx803/README.md#reason-of-problem-2

And  the issue had resovled on ROCm-4.3. We didn't need miopen patch on ROCm-4.3 any more.

**Comment by Davidportlouis** [comment]
> There is an already known issue on ROCm-4.2, that miopen treat xnack option different with hip.
> 
> https://github.com/xuhuisheng/rocm-build/blob/master/gfx803/README.md#reason-of-problem-2
> 
> And the issue had resolved on ROCm-4.3. We didn't need miopen patch on ROCm-4.3 any more.

Ok Thanks, I'll look into yet, also just one more query do we need rocrand and rocblas patch in ROCm-4.3 or they have been resolved too ?

**Comment by xuhuisheng** [comment]
We only need patch rocBLAS on ROCm-4.3, both rocRAND and MIOpen had been fixed.

**Comment by Davidportlouis** [comment]
> We only need patch rocBLAS on ROCm-4.3, both rocRAND and MIOpen had been fixed.

Ok thanks, I'll close this issue.
