### ISSUE TITLE
cuDNN version incompatibility: PyTorch was compiled against (2, 15, 0) but linked against (2, 16, 0)

### ISSUE THREAD

**Issue by andreaalf** [xuhuisheng/rocm-gfx803#13]
HI. I upgraded to rocm 5.1.1 by a fresh istallation. When i try to run a pytorch project i get that issue

**Comment by xuhuisheng** [comment]
Could you show me some testcase for re-produce this issue?

**Comment by andreaalf** [comment]
in this link you can find a jupyter notebook that reproduce this issue https://drive.google.com/file/d/1Q0JiJeAT7fQhXmtAskPGWVKadTgJZcwn/view?usp=sharing (you don't need to download any dataset, you can read the code and the logs by colab)

this is the error log
![image](https://user-images.githubusercontent.com/17101489/164194082-800ebd91-a9a0-4b15-b0b6-b70ecdbdc264.png)

**Comment by AlfaranoAndrea** [comment]
i tried also downgrading to pytorch for rocm5.0.0 and into other projects but i got the same issue. This error snippet maybe can be more explicative 
![image](https://user-images.githubusercontent.com/103185958/164684908-dd4f0fbb-0f24-441d-8275-37646e281dd2.png)

**Comment by xuhuisheng** [comment]
Looks like we need re-compile pytorch on ROCm-5.1.
Current version compiled on ROCm-5.0. so you can see MIOpen version is 2.15.0
