### ISSUE TITLE
Pytorch binaries not working on arch4edu ROCm

### ISSUE THREAD

**Issue by FranGamer1892** [xuhuisheng/rocm-gfx803#26]
Hello, I installed the ROCm stack from arch4edu and it seems to be working (rocminfo detects my RX 580). However, upon installing and testing torch (installed from the wheels provided here), this error pops up.

```
Traceback (most recent call last):
  File "pytest.py", line 4, in <module>
    import torch
  File "/home/fran/.local/lib/python3.8/site-packages/torch/__init__.py", line 199, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/fran/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: zgetrs_
```

I tried building torch myself but it didn't go so well, haha
I attempted to follow [this](https://github.com/xuhuisheng/rocm-build/blob/master/gfx803/README.md#workaround-1) but for instance, I don't seem to find the Arch equivalent of the packages installed by apt. Proceeding to build pytorch results in a bunch of errors, I couldn't really distinguish what the problem was.

**Comment by xuhuisheng** [comment]
Which version of ROCm do you use?
I didnot use arch before, But I can test related ROCm version with pytorch on this weekend.

**Comment by FranGamer1892** [comment]
I am not sure where to check, so I'll just send you the output from various commands, sorry haha

Thanks!

https://paste.debian.net/1269416/
https://paste.debian.net/1269417/
https://paste.debian.net/1269418/
https://paste.debian.net/1269419/

**Comment by xuhuisheng** [comment]
Looks like `Versión                   : 5.4.0-1`.

I will have a try this weekend.

**Comment by FranGamer1892** [comment]
Thank you!

**Comment by FranGamer1892** [comment]
Hello, I got around to building torch by myself and when I try testing it, this error pops up:
```
/usr/include/c++/12.2.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = const char*; _Alloc = std::allocator<const char*>; reference = const char*&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Abortado
```
Same error I had with the python-pytorch-rocm package from my distro's repositories. Unfortunately I can't find anything online. I built torch from release/1.12 using python 3.8. I had to set BUILD_TEST=OFF otherwise I couldn't build, and I had to change many things on the source code since my GCC version is too new.

**Comment by FranGamer1892** [comment]
Closing this as now there is a gfx803-compatible pytorch package in Arch repos, last time I checked it was on [community-testing]. Using a pytorch package built from source is also possible, but it's trickier to accomplish because of gcc/g++ 12 and other Arch-specific issues.
