### ISSUE TITLE
Update blender?

### ISSUE THREAD

**Issue by redthing1** [xuhuisheng/rocm-gfx803#28]
Hello,

Could you release an updated blender build please?

**Comment by xuhuisheng** [comment]
Which version of blender do you want?

**Comment by redthing1** [comment]
One of the 3.4.x please; the reason is because blender made breaking
changes to their format in 3.4. So your 3.3 build works great, but can't
open my 3.4 files. Would be awesome if you could build it. Thanks 🙏

**Comment by redthing1** [comment]
3.4.1

**Comment by xuhuisheng** [comment]
I may get a try on this weekend.

**Comment by redthing1** [comment]
Thank you, let me know.

**Comment by xuhuisheng** [comment]
@redthing1 
I rebuilt blender-3.4.1 for gfx803, The cube demo just fine. You can have a try.

<https://github.com/xuhuisheng/rocm-gfx803/releases/download/rocm541/blender-3.4.1-ubuntu2004-gfx803.tar.gz>

And here is some screenshot for blender-3.4.1.
<https://github.com/xuhuisheng/rocm-gfx803/blob/master/blender.md#blender-341-and-rocm-541>

**Comment by redthing1** [comment]
Awesome, thank you so much. I will try it

**Comment by redthing1** [comment]
I tried it: It works great! Can you post a source archive please? And just briefly explain what you had to change.

**Comment by xuhuisheng** [comment]
@redthing1 
The source of blender is too big to upload.

My modification is very simple, please read this markdown. Although it is for blender-3.3 and ROCm-5.3, I just do same patch on blender-3.4 with ROCm-5.4.1.

<https://github.com/xuhuisheng/rocm-gfx803/blob/master/blender.md>

1. modify intern/cycles/kernel/device/hip/compat.h, change all of `__noinline__` to `__inline__`
2. modify intern/cycles/device/hip/util.h, change 9 to 8, then cycles can use gfx803.

Then you could re-compile the hip kernel by yourself

```
/opt/rocm/bin/hipcc -Wno-parentheses-equality -Wno-unused-value \
  -O3 -ggdb -save-temps --amdgpu-target=gfx803 \
  -I /home/work/blender-git/blender/intern/cycles \
  --genco /home/work/blender-git/blender/intern/cycles/kernel/device/hip/kernel.cpp \
  -o "/home/work/blender-git/build_linux_cycles/bin/lib/kernel_gfx803.fatbin"
```

Finally we got the kernel fatbin file, put it to the related directory, like `YOUR_BLENDER_34_DIR/3.4/scripts/addons/cycles/lib/kernel_gfx803.fatbin`. restart blender, it will use our customized kernel next time.

**Comment by redthing1** [comment]
Thank you very much. I had tried and failed in the past, this method seems
to make Blender work 100% great on my RX580 ROCm. Thank you again.
