### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by Lunatik00** [xuhuisheng/rocm-gfx803#3]
Hi, i am trying to use this inside the dockers provided by amd for use with tensorflow, i have tried with 4.5.2 and 4.3.1, unfortunately they dont provide 4.5.0 or 4.3.0 with tensorflow, anyways, once i install the rocblas package the default installation of tensorflow doesn't work, which I think is expected, but i get an error when trying to install the wheel provided here
'''ERROR: tensorflow-2.6.0-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.'''

But I have successfully used your packages inside other dockers with rocm, so, one thing is to say, thanks for your efforts.
The error comes to the version of python (the one in the dockers with tensorflow preinstaled are 3.6 and the other docker is 3.8) and to ask if should I add a Docker option, i also tried to compile tensorflow for rocm 3.10 but i was not able to do it. I would like to contribute with those dockers and doing the compiles for at least a few extra versions, any info you could gave me to help with this would be appreciated.

PD: i dont know where to put this more as a comment than an issue, my issue was the compatibility with the dockers, which i was able to solve and i want to leave this if another person has the same problem, i think it would be a good idea to add this to the readme

**Comment by xuhuisheng** [comment]
So, you want gfx803 versioned rocblas for ROCm-4.5.2 and ROCm-4.3.1, and tensorflow-2.6.0 for python3.6?
I can go to build rocblas for 4.5.2, but tensorflow caused too much times, Could you try to upgrade your python from 3.6 to 3.8?

**Comment by Lunatik00** [comment]
It was to comment the error i got and to put which version worked fine, in reality i have to use python 3.7 for now, i tried 3.8 and i remember there was a problem that was not present in 3.7 in the libraries that i was using, i have found the instructions from amd to compile pytorch, but i have not been successful yet, if you documented the compilation process for pytorch and tensorflow i might be able to use that and share the resulting whl, I was successful now with installing your wheels in the docker of rocm 4.5.0, i will share that so people with this card can just run it, if i can do the same with python 3.7 and 3.6 i will share those too

**Comment by xuhuisheng** [comment]
The build script of phttps://github.com/bazelbuild/bazel/releases/download/3.7.2/bazel-3.7.2-installer-linux-x86_64.shython is here <https://github.com/xuhuisheng/rocm-build/tree/master/gfx803#workaround-1>

If you want to build tensorflow-rocm:

* install bazel first <https://github.com/bazelbuild/bazel/releases/download/3.7.2/bazel-3.7.2-installer-linux-x86_64.sh>
* clone <https://github.com/ROCmSoftwarePlatform/tensorflow-upstream>
* checkout r2.7-rocm-enhanced branch
* `python3 build_rocm_python3`, In my building server, cost about 3 hours.

**Comment by xuhuisheng** [comment]
This issue didn't update one years ago.
I will close it, please re-open if needed.
