### ISSUE TITLE
OSError: libmpi_cxx.so.40: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by andreaalf** [xuhuisheng/rocm-gfx803#7]
Hi! I'm trying to install Rocm5 with gfx803, and really thanks a lots for all your work!
I have Ubuntu 20.4.3
Kernel 5.11.0-27-generic
python 3.8.10

1. I installed ROCm using amdgpu tools following this guide https://docs.amd.com/bundle/ROCm_Installation_Guide-v5.0/page/How_To_Install_ROCm.html#_Installation_Methods, _I got no error or warning_
2. i follow your procedure installing rocblash, pytorch and torchvision 
3. at the ending of rocblash istallation i get this warming: 
_

> 503a092-cp38-cp38-linux_x86_64.whl
> _Collecting typing-extensions
>   Downloading typing_extensions-4.1.1-py3-none-any.whl (26 kB)
> Installing collected packages: typing-extensions, torch
>   WARNING: The scripts convert-caffe2-to-onnx, convert-onnx-to-caffe2 and torchrun are installed in '/home/fiss/.local/bin' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
> Successfully installed torch-1.11.0a0+git503a092 typing-extensions-4.1.1**_

_ 

So i add  the variable

> export PATH="$PATH:/home/fiss/.local/bin"  

to .bashrc for adding the directory to PATH

After the installation procedure from the terminal, if i try to import torch i obtain: 
> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fiss/.local/lib/python3.8/site-packages/torch/__init__.py", line 198, in <module>
    _load_global_deps()
  File "/home/fiss/.local/lib/python3.8/site-packages/torch/__init__.py", line 151, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmpi_cxx.so.40: cannot open shared object file: No such file or directory

What i can do? i'm very noob with linux but i'm sure that with your help we well overcome this issue
thanks for your attention

**Comment by xuhuisheng** [comment]
pytorch need install more dependencies manually.

```
sudo apt install -y liblmdb-dev libopencv-highgui-dev libopencv-contrib-dev libopenblas-dev
```

**Comment by andreaalf** [comment]
thanks for the fast reply!
now when i import torch i receive a different error code
> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fiss/.local/lib/python3.8/site-packages/torch/__init__.py", line 199, in <module>
    from torch._C import *  # noqa: F403
ImportError: libMIOpen.so.1: cannot open shared object file: No such file or directory

**Comment by xuhuisheng** [comment]
maybe the path changed.
you can try export LD_LIBRARY_PATH=/opt/rocm/lib , and run pytorch again.

**Comment by andreaalf** [comment]
thanks again for the support
i write on the terminal
> export LD_LIBRARY_PATH=/opt/rocm/lib 

and after i run python3 e tried to import pytorch, but i get the same previus error

**Comment by xuhuisheng** [comment]
please check whether there is /opt/rocm/lib/libmiopen.so.1

**Comment by andreaalf** [comment]
i went to /opt/rocm/lib/ folder and i list the folder file
there isn't any **libmiopen** file  in the directory

**Comment by xuhuisheng** [comment]
so we should find out where is libmiopen, maybe installation not successful.

**Comment by andreaalf** [comment]
first of all thanks for all your precious help effort
i cannot find libmiopen on the computer folders files. There is a way to install it?

**Comment by xuhuisheng** [comment]
miopen is a part of rocm-libs, likes rocblas, rocfft, we can get them after install rocm, the installation path is /opt/rocm
